### ISSUE TITLE
AttributeError: module 'dominate.tags' has no attribute 'input'

### ISSUE THREAD

**Issue by r-chris** [Knio/dominate#132]
Hello - we have been using the `dominate` python library for a while without issue and it has been a great utility for us. Today, I upgraded to the latest version (2.5.2) and noticed this error showing up. Is there a change in the API with the latest update in regards to this error or do you have any other idea what could have caused this for us?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/src/python/am/server/modules/login.py", line 575, in index
    form.add(html.input(type="hidden",
AttributeError: module 'dominate.tags' has no attribute 'input'
```

**Comment by golightlyb** [comment]
Looks like it broke here:

https://github.com/Knio/dominate/pull/131

**Comment by r-chris** [comment]
Ok, looks like a breaking API change. I would have expected a major version increase here, but I understand why this was changed.

**Comment by Knio** [comment]
I guess this should have been a major version bump.
